FROM rust:1.81

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    curl \
    && apt-get clean

COPY . .

WORKDIR /usr/src/app/example_workers/fast_response_rust_worker
RUN cargo install cargo-watch
RUN cargo build

RUN cp target/debug/fast_response_rust_worker /usr/local/bin/

