version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - "5420:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  phoenix:
    build:
      context: .
      dockerfile: Dockerfile.phoenix
    env_file: .env
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        mix deps.get &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 10s
      

  rust_worker:
    build:
      context: .
      dockerfile: Dockerfile.rust
    environment:
      - WORKER_ID=fast_running_rust_worker
      - WORKER_ADDRESS=rust_worker:50053
      - QUEUE_ADDRESS=http://phoenix:50051
    ports:
      - "50055:50055"
    volumes:
      - ./example_workers/fast_response_rust_worker:/usr/src/app/example_workers/fast_response_rust_worker
    depends_on:
      phoenix:
        condition: service_healthy
    command: >
      sh -c "
        /usr/local/bin/fast_response_rust_worker --worker-server-address=0.0.0.0:50055 --worker-id=fast_running-rust_worker --worker-address=rust_worker:50055 --queue-address=$QUEUE_ADDRESS --queue-name=media_update
      "


  rust_worker_2:
    build:
      context: .
      dockerfile: Dockerfile.rust
    environment:
      - WORKER_ID=fast_running_rust_worker_2
      - WORKER_ADDRESS=rust_worker:50054
      - QUEUE_ADDRESS=http://phoenix:50051
    ports:
      - "50054:50054"
    volumes:
      - ./example_workers/fast_response_rust_worker:/usr/src/app/example_workers/fast_response_rust_worker
    depends_on:
      phoenix:
        condition: service_healthy
    command: >
      sh -c "
        /usr/local/bin/fast_response_rust_worker --worker-server-address=0.0.0.0:50054 --worker-id=fast_running-rust_worker_2 --worker-address=rust_worker_2:50054 --queue-address=$QUEUE_ADDRESS --queue-name=image_processing
      "

volumes:
  postgres_data:
    name: postgres_data_fresh