FROM elixir:1.17.3

WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    npm \
    && apt-get clean

RUN mix local.hex --force && mix local.rebar --force

COPY . .

RUN mix deps.get
RUN npm --prefix ./assets install
RUN npm --prefix ./assets run deploy

EXPOSE 4000
EXPOSE 50051