name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check Fly Status
        run: |
          echo "Checking Fly.io status..."
          flyctl status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify Database Attachment
        run: |
          echo "Checking database attachment..."
          flyctl postgres attach peregrinequeue-db || echo "Database already attached"
          flyctl config show
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          echo "Starting deployment..."
          flyctl deploy --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run Migrations
        run: |
          echo "Attempting to run migrations..."
          flyctl ssh console -C 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}